/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Appointment,
} from './components/date-picker/date-picker.interface';


export namespace Components {

  interface DatePicker {
    'appointments': Appointment[];
    'from': string;
    'name': string;
    'till': string;
  }
  interface DatePickerAttributes extends StencilHTMLAttributes {
    'appointments'?: Appointment[];
    'from'?: string;
    'name'?: string;
    'till'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DatePicker': Components.DatePicker;
  }

  interface StencilIntrinsicElements {
    'date-picker': Components.DatePickerAttributes;
  }


  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLElementTagNameMap {
    'date-picker': HTMLDatePickerElement
  }

  interface ElementTagNameMap {
    'date-picker': HTMLDatePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
